# Generated by Django 3.2.5 on 2021-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amphibian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default=None, max_length=50)),
                ('scientific_name', models.CharField(default=None, max_length=50)),
                ('type', models.CharField(choices=[('newt', 'Newt'), ('toad', 'Toad'), ('frog', 'Frog')], default='newt', max_length=10)),
                ('image', models.CharField(default=None, max_length=200)),
                ('native', models.CharField(choices=[('native', 'Native'), ('non-native', 'Non-Native')], default='native', max_length=20)),
                ('identification', models.TextField(default=None)),
                ('fact', models.TextField(default=None)),
                ('distribution', models.TextField(default=None)),
                ('life_cycle', models.TextField(default=None)),
                ('protection', models.TextField(default=None)),
                ('conservation_status', models.CharField(choices=[('EX', 'Extinct'), ('EW', 'Extinct in the Wild'), ('CR', 'Critically Endangered'), ('EN', 'Endangered'), ('VU', 'Vulnerable'), ('NT', 'Not Threatened'), ('CD', 'Conservation Dependent'), ('LC', 'Least Concern'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], default='DD', max_length=30)),
                ('about', models.TextField(default=None)),
            ],
        ),
    ]
