# Generated by Django 3.2.5 on 2021-07-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amphibians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amphibian',
            name='common_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='amphibian',
            name='image',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='amphibian',
            name='native',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amphibian',
            name='scientific_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='amphibian',
            name='type',
            field=models.CharField(choices=[('newt', 'Newt'), ('toad', 'Toad'), ('frog', 'Frog')], default='newt', max_length=10),
        ),
    ]
