# Generated by Django 3.2.5 on 2021-07-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amphibians', '0002_auto_20210723_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amphibian',
            name='native',
            field=models.CharField(choices=[('native', 'Native'), ('non-native', 'Non-Native')], default='native', max_length=20),
        ),
    ]
