# Generated by Django 3.2.5 on 2021-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('spotted_on', models.DateTimeField()),
                ('location_x', models.CharField(max_length=15)),
                ('location_y', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_habitat', models.CharField(choices=[('natpond', 'Natural Pond'), ('manpond', 'Man-Made Pond'), ('natstrean', 'Natural Stream'), ('marsh', 'Marsh'), ('river', 'River')], default='natpond', max_length=15)),
                ('land_habitat', models.CharField(choices=[('wood', 'Woodland'), ('field', 'Open Field'), ('garden', 'Garden'), ('urban', 'Urban')], default='wood', max_length=15)),
            ],
        ),
    ]
