# Generated by Django 3.2.5 on 2021-07-26 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('spotted_on', models.DateTimeField()),
                ('location_x', models.CharField(max_length=15)),
                ('location_y', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_habitat', models.CharField(choices=[('natpond', 'Natural Pond'), ('manpond', 'Man-Made Pond'), ('natstrean', 'Natural Stream'), ('marsh', 'Marsh'), ('river', 'River')], default='natpond', max_length=15)),
                ('land_habitat', models.CharField(choices=[('wood', 'Woodland'), ('field', 'Open Field'), ('garden', 'Garden'), ('urban', 'Urban')], default='wood', max_length=15)),
                ('county', models.CharField(choices=[('avo', 'Avon'), ('bed', 'Bedfordshire'), ('ber', 'Berkshire'), ('buc', 'Buckinghamshire'), ('cam', 'Cambridgeshire'), ('che', 'Cheshire'), ('cle', 'Cleveland'), ('cor', 'Cornwall'), ('cd', 'County Durham'), ('cum', 'Cumbria'), ('der', 'Derbyshire'), ('dev', 'Devon'), ('dor', 'Dorset'), ('es', 'East Sussex'), ('esx', 'Essex'), ('glo', 'Gloucestershire'), ('ham', 'Hampshire'), ('here', 'Herefordshire'), ('hert', 'Hertfordshire'), ('iow', 'Isle of Wight'), ('ken', 'Kent'), ('lan', 'Lancashire'), ('lei', 'Leicestershire'), ('lin', 'Lincolnshire'), ('lon', 'London'), ('mer', 'Merseyside'), ('mid', 'Middlesex'), ('norf', 'Norfolk'), ('nh', 'North Humberside'), ('ny', 'North Yorkshire'), ('northam', 'Northamptonshire'), ('northum', 'Northumberland'), ('not', 'Nottinghamshire'), ('oxf', 'Oxfordshire'), ('shr', 'Shropshire'), ('som', 'Somerset'), ('sh', 'South Humberside'), ('sy', 'South Yorkshire'), ('sta', 'Staffordshire'), ('suf', 'Suffolk'), ('sur', 'Surrey'), ('tw', 'Tyne and Wear'), ('war', 'Warwickshire'), ('wm', 'West Midlands'), ('ws', 'West Sussex'), ('wy', 'West Yorkshire'), ('wil', 'Wiltshire'), ('wor', 'Worcestershire'), ('clw', 'Clwyd'), ('dyf', 'Dyfed'), ('gwe', 'Gwent'), ('gwy', 'Gwynedd'), ('mg', 'Mid Glamorgan'), ('sg', 'South Glamorgan'), ('wg', 'West Glamorgan'), ('pow', 'Powys'), ('', 'Aberdeenshire'), ('', 'Angus'), ('', 'Argyll'), ('', 'Ayrshire'), ('', 'Banffshire'), ('', 'Berwickshire'), ('', 'Buteshire (or the County of Bute)'), ('', 'Caithness'), ('', 'Clackmannanshire'), ('', 'Dumfriesshire'), ('', 'Dunbartonshire'), ('', 'East Lothian'), ('', 'Fife'), ('', 'Inverness-shire'), ('', 'Kincardineshire'), ('', 'Kinross-shire'), ('', 'Kirkcudbrightshire'), ('', 'Lanarkshire'), ('', 'Midlothian'), ('', 'Moray'), ('', 'Nairnshire'), ('', 'Orkney'), ('', 'Peebleshire'), ('', 'Perthshire'), ('', 'Renfrewshire'), ('', 'Ross and Cromarty'), ('', 'Roxburghshire'), ('', 'Selkirkshire'), ('', 'Shetland'), ('', 'tirlingshire'), ('', 'Sutherland'), ('', 'West Lothian'), ('', 'Wigtownshire')], default='none', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Surveys_Submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
