# Generated by Django 3.2.5 on 2021-07-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
    ]
