# Generated by Django 3.2.5 on 2021-07-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20210727_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='land_habitat',
            field=models.CharField(choices=[('1', 'Woodland'), ('2', 'Open Field'), ('3', 'Garden'), ('4', 'Urban')], default='wood', max_length=15),
        ),
        migrations.AlterField(
            model_name='survey',
            name='water_habitat',
            field=models.CharField(choices=[('1', 'Natural Pond'), ('2', 'Man-Made Pond'), ('3', 'Natural Stream'), ('4', 'Marsh'), ('5', 'River')], default='natpond', max_length=15),
        ),
    ]
