# Generated by Django 3.2.5 on 2021-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20210727_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='county',
            field=models.CharField(choices=[('1', 'Avon'), ('2', 'Bedfordshire'), ('3', 'Berkshire'), ('4', 'Buckinghamshire'), ('5', 'Cambridgeshire'), ('che', 'Cheshire'), ('cle', 'Cleveland'), ('cor', 'Cornwall'), ('cd', 'County Durham'), ('cum', 'Cumbria'), ('der', 'Derbyshire'), ('dev', 'Devon'), ('dor', 'Dorset'), ('es', 'East Sussex'), ('esx', 'Essex'), ('glo', 'Gloucestershire'), ('ham', 'Hampshire'), ('here', 'Herefordshire'), ('hert', 'Hertfordshire'), ('iow', 'Isle of Wight'), ('ken', 'Kent'), ('lan', 'Lancashire'), ('lei', 'Leicestershire'), ('lin', 'Lincolnshire'), ('lon', 'London'), ('mer', 'Merseyside'), ('mid', 'Middlesex'), ('norf', 'Norfolk'), ('nh', 'North Humberside'), ('ny', 'North Yorkshire'), ('northam', 'Northamptonshire'), ('northum', 'Northumberland'), ('not', 'Nottinghamshire'), ('oxf', 'Oxfordshire'), ('shr', 'Shropshire'), ('som', 'Somerset'), ('sh', 'South Humberside'), ('sy', 'South Yorkshire'), ('sta', 'Staffordshire'), ('suf', 'Suffolk'), ('sur', 'Surrey'), ('tw', 'Tyne and Wear'), ('war', 'Warwickshire'), ('wm', 'West Midlands'), ('ws', 'West Sussex'), ('wy', 'West Yorkshire'), ('wil', 'Wiltshire'), ('wor', 'Worcestershire'), ('clw', 'Clwyd'), ('dyf', 'Dyfed'), ('gwe', 'Gwent'), ('gwy', 'Gwynedd'), ('mg', 'Mid Glamorgan'), ('sg', 'South Glamorgan'), ('wg', 'West Glamorgan'), ('pow', 'Powys'), ('abe', 'Aberdeenshire'), ('ang', 'Angus'), ('arg', 'Argyll'), ('ayr', 'Ayrshire'), ('banf', 'Banffshire'), ('ber', 'Berwickshire'), ('but', 'Buteshire'), ('cai', 'Caithness'), ('cla', 'Clackmannanshire'), ('dum', 'Dumfriesshire'), ('dun', 'Dunbartonshire'), ('el', 'East Lothian'), ('fif', 'Fife'), ('inv', 'Inverness-shire'), ('kinc', 'Kincardineshire'), ('kinr', 'Kinross-shire'), ('kir', 'Kirkcudbrightshire'), ('lan', 'Lanarkshire'), ('mid', 'Midlothian'), ('mor', 'Moray'), ('nai', 'Nairnshire'), ('ork', 'Orkney'), ('pee', 'Peebleshire'), ('per', 'Perthshire'), ('ren', 'Renfrewshire'), ('rc', 'Ross and Cromarty'), ('rox', 'Roxburghshire'), ('sel', 'Selkirkshire'), ('she', 'Shetland'), ('tir', 'tirlingshire'), ('sut', 'Sutherland'), ('wl', 'West Lothian'), ('wig', 'Wigtownshire'), ('none', 'None')], default='none', max_length=30),
        ),
    ]
