# Generated by Django 3.2.5 on 2021-07-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='location_x',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='location_y',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
