# Generated by Django 3.2.5 on 2021-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='image2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='image3',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
